"minimal
filetype plugin indent on
syntax on
set backspace=indent,eol,start "backspace with indent
set hidden "allow switch buffer without save file
set noswapfile "no generate .swp files
set ignorecase smartcase "para hacer busqueda con minus o mayus si escribes en minuscula.

"to use :find  with current directory files recursively
set path=.,**

" Split window
nmap ss :split<Return><C-w>w
nmap sv :vsplit<Return><C-w>w
" Move window
nmap <Space> <C-w>w
map s<left> <C-w>h
map s<up> <C-w>k
map s<down> <C-w>j
map s<right> <C-w>l
map sh <C-w>h
map sk <C-w>k
map sj <C-w>j
map sl <C-w>l
" Resize window
nmap <C-w><left> <C-w><
nmap <C-w><right> <C-w>>
nmap <C-w><up> <C-w>+
nmap <C-w><down> <C-w>-
"zoom window
noremap Zz <c-w>_ \| <c-w>\|
noremap Zo <c-w>=

